# Workflow for deploying RepoBee to PyPi

name: deploy

on:
  release:
    types: published

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Package RepoBee
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements/app.txt
        python -m pip install .
        python setup.py sdist bdist_wheel
    - name: Publish RepoBee to PyPi
      uses: pypa/gh-action-pypi-publish@5d1679fa6b895587c6eb10c3fe82205b440a580e # v1.6.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
